export { Home } from "./Home";
export { MovieDetails } from "./MovieDetails"; 
export { Movies } from "./Movies";
export { Series } from "./Series";
export { SeriesDetails } from "./SeriesDetails";
export { Actors } from './Actors'
export { Busqueda } from './Busqueda'
export { Categories } from './Categories'
export { SeasonsDetails } from './SeasonsDetails'